DSEG	SEGMENT
	char	DW	4 DUP(0)
	inta	DW	7 DUP(0)
	float	DW	1 DUP(0)
	TEMP	DW	8 DUP(0)
	CONST	DW	2,1,0,3,5,15,8
DSEG	ENDS
CSEG	SEGMENT
	ASSUME	CS:CSEG,DS:DSEG
start:	MOV	AX,DSEG
	MOV	DS,AX
	MOV	AX,CONST[0]
	MOV	char[8],AX
	MOV	AX,CONST[2]
	MOV	char[10],AX
	MOV	AX,CONST[4]
	MOV	char[12],AX
	MOV	AX,CONST[4]
	MOV	BX,CONST[2]
	ADD	AX,BX
	MOV	TEMP[0],AX
	MOV	AX,TEMP[0]
	AND	AX,AX
	JZ	
	MOV	AX,CONST[10]
	MOV	BX,char[8]
	SUB	AX,BX
	MOV	char[12],AX
	MOV	AX,CONST[12]
	MOV	char[14],AX
	MOV	AX,CONST[12]
	MOV	char[16],AX
	MOV	AX,CONST[0]
	MOV	char[18],AX
t0:	MOV	AX,CONST[0]
	MOV	BX,char[10]
	MUL	BX
	MOV	TEMP[10],AX
	MOV	AX,char[8]
	MOV	BX,TEMP[10]
	SUB	AX,BX
	MOV	TEMP[12],AX
	MOV	AX,TEMP[12]
	AND	AX,AX
	JZ	t1
	MOV	AX,char[8]
	MOV	BX,char[10]
	ADD	AX,BX
	MOV	char[12],AX
	JMP	t0
t1:	MOV	AX,CONST[6]
	MOV	char[22],AX
CSEG	ENDS
	END	START
