DSEG	SEGMENT
	test	DW	2 DUP(0)
	bb	DW	10 DUP(0)
	char	DW	6 DUP(0)
	inta	DW	11 DUP(0)
	float	DW	2 DUP(0)
	TEMP	DW	8 DUP(0)
	CONST	DW	4,12,22,3,5,10,1,0,2,6,0,0,0,0,0,0,0,0,0,0,0,16,8
DSEG	ENDS
CSEG	SEGMENT
	ASSUME	CS:CSEG,DS:DSEG
FUNC	PROC	NEAR
	MOV	AX,TEMP[0]
	CALL	COUT
	RET
FUNC	ENDP
FUNCTT	PROC	NEAR
	MOV	AX,CONST[4]
	MOV	char[10],AX
	CALL	FUNC
	MOV	AX,TEMP[2]
	CALL	COUT
	RET
FUNCTT	ENDP
MAX	PROC	NEAR
	MOV	AX,char[14]
	MOV	BX,char[16]
	CMP	AX,BX
	MOV	TEMP[4],AX
	MOV	AX,TEMP[4]
	AND	AX,AX
	JZ	t0
	MOV	AX,char[16]
	MOV	char[18],AX
t0:	MOV	AX,char[18]
	MOV	BX,CONST[6]
	ADD	AX,BX
	MOV	char[18],AX
	RET
MAX	ENDP
COUT	PROC	NEAR
	MOV	SI,10
	MOV	CX,0
next1:	MOV	DX,0
	DIV	SI
	PUSH	DX
	INC	CX
	CMP	AX,0
	JNZ	next1
next2:	POP	DX
	ADD	DL,30H
	MOV	AH,02H
	INT	21H
	LOOP	next2
	RET
COUT	ENDP
start:	MOV	AX,DSEG
	MOV	DS,AX
	MOV	AX,test[0]
	MOV	TEMP[8],AX
	MOV	AX,char[20]
	MOV	test[0],AX
	MOV	AX,test[2]
	MOV	char[34],AX
	MOV	AX,CONST[10]
	MOV	char[22],AX
	MOV	AX,CONST[6]
	MOV	char[14],AX
	MOV	AX,CONST[0]
	MOV	char[16],AX
	CALL	MAX
	MOV	AX,char[20]
	MOV	char[18],AX
	CALL	FUNCTT
	MOV	AX,CONST[14]
	MOV	char[24],AX
	MOV	AX,bb[4]
	MOV	TEMP[12],AX
	MOV	AX,CONST[18]
	MOV	bb[4],AX
	MOV	AX,bb[4]
	MOV	char[22],AX
CSEG	ENDS
	END	START
